include:
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/deployment-service/lulu/docker-deploy.yml'
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/deployment-service/museo/docker-deploy.yml'

stages:
  - deploy

.deploy:
  variables:
    FORCE_DOCKER_COMPOSE: 1
    SERVICES_TO_CHECK: pihole-primary

.deploy-secondary:
  variables:
    COMPOSE_FILE: compose.secondary.yaml
    SERVICES_TO_CHECK: pihole-secondary


.deploy-lulu-secondary:
  extends:
    - .deploy-lulu
    - .deploy-secondary
  environment:
    name: lulu-secondary

deploy-branch-lulu-secondary:
  extends:
    - .deploy-lulu-secondary
    - .deploy-branch

deploy-tag-lulu-secondary:
  extends:
    - .deploy-lulu-secondary
    - .deploy-tag


.deploy-museo-secondary:
  extends:
    - .deploy-museo
    - .deploy-secondary
  environment:
    name: museo-secondary

deploy-branch-museo-secondary:
  extends:
    - .deploy-museo-secondary
    - .deploy-branch

deploy-tag-museo-secondary:
  extends:
    - .deploy-museo-secondary
    - .deploy-tag
