services:
  pihole:
    image: ${IMAGE_NAME:-pihole/pihole}:${IMAGE_TAG:-latest}
    environment:
      TZ:
      ADMIN_EMAIL:
      WEBPASSWORD:
      PIHOLE_DNS_:
      DNSMASQ_LISTENING:
      DNSSEC:
      DNS_BOGUS_PRIV:
      DNS_FQDN_REQUIRED:
      REV_SERVER:
      REV_SERVER_DOMAIN:
      REV_SERVER_TARGET:
      REV_SERVER_CIDR:
      DHCP_ACTIVE:
      DHCP_START:
      DHCP_END:
      DHCP_ROUTER:
      DHCP_LEASETIME:
      PIHOLE_DOMAIN:
      DHCP_IPv6:
      DHCP_rapid_commit:
      FTLCONF_LOCAL_IPV4:
      FTLCONF_LOCAL_IPV6:
    hostname: ${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}
    networks:
      traefik-net:
    ports:
      - target: ${DNS_INTERNAL_PORT}
        published: ${DNS_EXTERNAL_PORT}
        protocol: tcp
        mode: ${DNS_PORT_MODE}
      - target: ${DNS_INTERNAL_PORT}
        published: ${DNS_EXTERNAL_PORT}
        protocol: udp
        mode: ${DNS_PORT_MODE}
      - target: ${DHCP_INTERNAL_PORT}
        published: ${DHCP_EXTERNAL_PORT}
        protocol: udp
        mode: ${DHCP_PORT_MODE}
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
      - SYS_NICE
      - CHOWN
    volumes:
      - pihole-vol:/etc/pihole
      - dnsmasqd-vol:/etc/dnsmasq.d
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - ${PLACEMENT_CONSTRAINTS_NAME:-node.hostname} ${PLACEMENT_CONSTRAINTS_OPERATOR:-==} ${PLACEMENT_CONSTRAINTS_VALUE:-node}
      restart_policy:
        delay: ${RESTART_DELAY:-1s}
      labels:
        traefik.enable: ${TRAEFIK_ENABLE:-true}
        traefik.http.routers.pihole.entrypoints: ${TRAEFIK_ENTRYPOINT:-https}
        traefik.http.routers.pihole.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)
        traefik.http.middlewares.pihole-add-prefix.addprefix.prefix: ${DASHBOARD_PREFIX:-/admin}
        traefik.http.routers.pihole.middlewares: pihole-add-prefix
        traefik.http.services.pihole.loadbalancer.server.port: ${DASHBOARD_PORT:-80}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-128M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-64M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

volumes:
  pihole-vol:
    name: ${PIHOLE_VOL_NAME}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${PIHOLE_VOL_DEVICE}

  dnsmasqd-vol:
    name: ${DNSMASQD_VOL_NAME}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${DNSMASQD_VOL_DEVICE}
