version: '3.7'

services:
  pihole:
    image: ${IMAGE_NAME:-pihole/pihole}:${IMAGE_TAG:-latest}
    environment:
      TZ:
      WEBPASSWORD:
      DNS1:
      DNS2:
      DNSMASQ_LISTENING:
      VIRTUAL_HOST: ${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}
    networks:
      traefik-net:
    ports:
      - target: ${DNS_INTERNAL_PORT}
        published: ${DNS_PORT}
        protocol: tcp
        mode: ${PORT_MODE}
      - target: ${DNS_INTERNAL_PORT}
        published: ${DNS_PORT}
        protocol: udp
        mode: ${PORT_MODE}
    hostname: ${TRAEFIK_SUBDOMAIN}{{.Task.Slot}}.${TRAEFIK_DOMAIN}
    extra_hosts:
      - ${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}:${TRAEFIK_LOCAL_IP}
      - ${TRAEFIK_DOMAIN}:${TRAEFIK_LOCAL_IP}
      - alertmanager.${TRAEFIK_DOMAIN}:${TRAEFIK_LOCAL_IP}
      - backup.${TRAEFIK_DOMAIN}:${TRAEFIK_LOCAL_IP}
      - grafana.${TRAEFIK_DOMAIN}:${TRAEFIK_LOCAL_IP}
      - motion.${TRAEFIK_DOMAIN}:${TRAEFIK_LOCAL_IP}
      - motioneye.${TRAEFIK_DOMAIN}:${TRAEFIK_LOCAL_IP}
      - mulo.${TRAEFIK_DOMAIN}:${TRAEFIK_LOCAL_IP}
      - portainer.${TRAEFIK_DOMAIN}:${TRAEFIK_LOCAL_IP}
      - prometheus.${TRAEFIK_DOMAIN}:${TRAEFIK_LOCAL_IP}
      - pushgateway.${TRAEFIK_DOMAIN}:${TRAEFIK_LOCAL_IP}
      - seafile.${TRAEFIK_DOMAIN}:${TRAEFIK_LOCAL_IP}
      - tajinaste.${TRAEFIK_DOMAIN}:${TRAEFIK_LOCAL_IP}
      - traefik.${TRAEFIK_DOMAIN}:${TRAEFIK_LOCAL_IP}
      - transmission.${TRAEFIK_DOMAIN}:${TRAEFIK_LOCAL_IP}
      - tts.${TRAEFIK_DOMAIN}:${TRAEFIK_LOCAL_IP}
    dns:
      - 127.0.0.1
      - ${DNS1}
      - ${DNS2}
    volumes:
      - pihole-vol:/etc/pihole
      - dnsmasqd-vol:/etc/dnsmasq.d
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-2}
      restart_policy:
        delay: ${RESTART_DELAY:-3s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      placement:
        constraints:
          - ${PLACEMENT_CONSTRAINT:-node.labels.dns == 1}
      labels:
        traefik.enable: 'true'
        traefik.http.routers.pihole.entrypoints: ${TRAEFIK_ENTRYPOINT:-https}
        traefik.http.routers.pihole.tls.certresolver: ${TRAEFIK_CERTRESOLVER:-default}
        traefik.http.routers.pihole.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)
        traefik.http.middlewares.pihole-prefix.addprefix.prefix: ${DASHBOARD_PREFIX:-/admin}
        traefik.http.routers.pihole.middlewares: pihole-prefix
        traefik.http.services.pihole.loadbalancer.server.port: ${DASHBOARD_PORT:-80}
        traefik.http.services.pihole.loadbalancer.sticky.cookie.name: ${TRAEFIK_COOKIE_NAME:-sticky}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-128M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-32M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

volumes:
  pihole-vol:
    name: ${PIHOLE_VOL_NAME:-pihole-vol}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDRESS},${VOL_OPTIONS}
      device: ${PIHOLE_VOL_DEVICE:-:/pihole-vol/}

  dnsmasqd-vol:
    name: ${DNSMASQD_VOL_NAME:-dnsmasqd-vol}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDRESS},${VOL_OPTIONS}
      device: ${DNSMASQD_VOL_DEVICE:-:/dnsmasqd-vol/}
