version: '3.9'

services:
  pihole:
    image: ${IMAGE_NAME:-pihole/pihole}:${IMAGE_TAG:-latest}
    environment:
      TZ:
      ADMIN_EMAIL:
      WEBPASSWORD:
      PIHOLE_DNS_:
      DNSMASQ_LISTENING:
      DNSSEC:
      DNS_BOGUS_PRIV:
      DNS_FQDN_REQUIRED:
      REV_SERVER:
      REV_SERVER_DOMAIN:
      REV_SERVER_TARGET:
      REV_SERVER_CIDR:
      DHCP_ACTIVE:
      DHCP_START:
      DHCP_END:
      DHCP_ROUTER:
      DHCP_LEASETIME:
      PIHOLE_DOMAIN:
      DHCP_IPv6:
      DHCP_rapid_commit:
      FTLCONF_LOCAL_IPV4:
      FTLCONF_LOCAL_IPV6:
      VIRTUAL_HOST:
    networks:
      pihole-net:
    ports:
      - target: ${DNS_INTERNAL_PORT}
        published: ${DNS_EXTERNAL_PORT}
        protocol: tcp
        mode: ${DNS_PORT_MODE}
      - target: ${DNS_INTERNAL_PORT}
        published: ${DNS_EXTERNAL_PORT}
        protocol: udp
        mode: ${DNS_PORT_MODE}
      - target: ${DHCP_INTERNAL_PORT}
        published: ${DHCP_EXTERNAL_PORT}
        protocol: udp
        mode: ${DHCP_PORT_MODE}
      - target: ${DASHBOARD_INTERNAL_PORT}
        published: ${DASHBOARD_EXTERNAL_PORT}
        protocol: tcp
        mode: ${DASHBOARD_PORT_MODE}
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
      - SYS_NICE
      - CHOWN
    volumes:
      - pihole-vol:/etc/pihole
      - dnsmasqd-vol:/etc/dnsmasq.d
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.${PLACEMENT_CONSTRAINTS_NODE_LABELS_NAME} == ${PLACEMENT_CONSTRAINTS_NODE_LABELS_VALUE}
      restart_policy:
        delay: ${RESTART_DELAY:-1s}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-128M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-64M}

networks:
  pihole-net:
    name: ${PIHOLE_NET_NAME:-pihole-net}
    driver: ${PIHOLE_NET_DRIVER:-overlay}
    attachable: true

volumes:
  pihole-vol:
    name: ${PIHOLE_VOL_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${PIHOLE_VOL_DEVICE}

  dnsmasqd-vol:
    name: ${DNSMASQD_VOL_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${DNSMASQD_VOL_DEVICE}
