include:
  - compose.common-toplevel.yaml

services:
  pihole-primary:
    extends:
      file: compose.common-service.yaml
      service: pihole
    container_name: ${CONTAINER_NAME:-pihole-primary}
    environment:
      FTLCONF_dhcp_active:
      FTLCONF_dhcp_start:
      FTLCONF_dhcp_end:
      FTLCONF_dhcp_router:
      FTLCONF_dhcp_leaseTime:
      FTLCONF_dns_domain:
      FTLCONF_dhcp_ipv6:
      FTLCONF_dhcp_rapidCommit:
      FTLCONF_dhcp_multiDNS:
      FTLCONF_dhcp_ignoreUnknownClients:
    dns:
      - 127.0.0.1
      - ${BACKUP_DNS:-8.8.8.8}
    cap_add:
      - NET_RAW
      - NET_ADMIN
