services:
  pihole:
    image: ${IMAGE_NAME:-pihole/pihole}:${IMAGE_TAG:-latest}
    environment:
      TZ:
      TAIL_FTL_LOG:
      FTLCONF_webserver_api_password:
      FTLCONF_webserver_port:
      FTLCONF_misc_etc_dnsmasq_d:
      FTLCONF_dns_reply_host_IPv4:
      FTLCONF_dns_reply_host_IPv6:
      FTLCONF_dns_upstreams:
      FTLCONF_dns_listeningMode:
      FTLCONF_dns_dnssec:
      FTLCONF_dns_bogusPriv:
      FTLCONF_dns_domainNeeded:
      FTLCONF_dns_revServers:
    network_mode: host
    volumes:
      - pihole-vol:/etc/pihole
      - dnsmasqd-vol:/etc/dnsmasq.d
    cap_add:
      - NET_BIND_SERVICE
      - SYS_NICE
      - CHOWN
    restart: always
    cpus: '${CPUS:-1}'
    mem_limit: ${MEM_LIMIT:-512M}
    mem_reservation: ${MEM_RESERVATION:-256M}
