include:
  - compose.common-toplevel.yaml

services:
  pihole-primary:
    extends:
      file: compose.common-service.yaml
      service: pihole
    environment:
      DHCP_ACTIVE:
      DHCP_START:
      DHCP_END:
      DHCP_ROUTER:
      DHCP_LEASETIME:
      PIHOLE_DOMAIN:
      DHCP_IPv6:
      DHCP_rapid_commit:
    dns:
      - 127.0.0.1
      - ${BACKUP_DNS:-8.8.8.8}
    cap_add:
      - NET_ADMIN
