include:
  - compose.common-toplevel.yaml

services:
  pihole-secondary:
    extends:
      file: compose.common-service.yaml
      service: pihole
    container_name: ${CONTAINER_NAME:-pihole-secondary}
