services:
  pihole:
    image: ${PIHOLE_IMAGE_NAME:-pihole/pihole}:${PIHOLE_IMAGE_TAG:-latest}
    environment:
      TZ:
      ADMIN_EMAIL:
      WEBPASSWORD:
      WEB_PORT:
      PIHOLE_DNS_:
      DNSMASQ_LISTENING:
      DNSSEC:
      DNS_BOGUS_PRIV:
      DNS_FQDN_REQUIRED:
      REV_SERVER:
      REV_SERVER_DOMAIN:
      REV_SERVER_TARGET:
      REV_SERVER_CIDR:
      DHCP_ACTIVE:
      DHCP_START:
      DHCP_END:
      DHCP_ROUTER:
      DHCP_LEASETIME:
      PIHOLE_DOMAIN:
      DHCP_IPv6:
      DHCP_rapid_commit:
      FTLCONF_LOCAL_IPV4:
      FTLCONF_LOCAL_IPV6:
    networks:
      host-net:
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
      - SYS_NICE
      - CHOWN
    volumes:
      - pihole-vol:/etc/pihole
      - dnsmasqd-vol:/etc/dnsmasq.d
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - ${PLACEMENT_CONSTRAINTS_NAME:-node.hostname} ${PLACEMENT_CONSTRAINTS_OPERATOR:-==} ${PLACEMENT_CONSTRAINTS_VALUE:-node}
      restart_policy:
        delay: ${PIHOLE_RESTART_DELAY:-1s}
      resources:
        limits:
          cpus: '${PIHOLE_RESOURCES_LIMITS_CPUS:-1}'
          memory: ${PIHOLE_RESOURCES_LIMITS_MEMORY:-512M}
        reservations:
          cpus: '${PIHOLE_RESOURCES_RESERVATIONS_CPUS:-0.01}'
          memory: ${PIHOLE_RESOURCES_RESERVATIONS_MEMORY:-256M}

  pihole-proxy:
    image: ${PROXY_IMAGE_NAME:-caddy}:${PROXY_IMAGE_TAG:-latest}
    environment:
      CADDY_PORT:
      BACKEND_ADDR:
    networks:
      traefik-net:
    configs:
      - source: caddyfile-config
        target: /etc/caddy/Caddyfile
    healthcheck:
      test: wget --spider -q http://localhost:${CADDY_PORT}/health
      interval: ${PROXY_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${PROXY_HEALTHCHECK_TIMEOUT:-5s}
      retries: ${PROXY_HEALTHCHECK_RETRIES:-10}
      start_period: ${PROXY_HEALTHCHECK_START_PERIOD:-30s}
    deploy:
      mode: replicated
      replicas: ${PROXY_REPLICAS:-1}
      restart_policy:
        delay: ${PROXY_RESTART_DELAY:-10s}
      update_config:
        delay: ${PROXY_UPDATE_DELAY:-1m}
      labels:
        traefik.enable: ${TRAEFIK_ENABLE}
        traefik.http.routers.pihole.entrypoints: ${TRAEFIK_ENTRYPOINT:-https}
        traefik.http.routers.pihole.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)
        traefik.http.services.pihole.loadbalancer.server.port: ${CADDY_PORT}
      resources:
        limits:
          cpus: '${PROXY_RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${PROXY_RESOURCES_LIMITS_MEMORY:-128M}
        reservations:
          cpus: '${PROXY_RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${PROXY_RESOURCES_RESERVATIONS_MEMORY:-64M}

networks:
  host-net:
    name: ${HOST_NET_NAME:-host}
    driver: ${HOST_NET_DRIVER:-host}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

volumes:
  pihole-vol:
    name: ${PIHOLE_VOL_NAME}
    driver: ${VOL_DRIVER}

  dnsmasqd-vol:
    name: ${DNSMASQD_VOL_NAME}
    driver: ${VOL_DRIVER}

configs:
  caddyfile-config:
    name: ${CADDYFILE_CONFIG_NAME:-pihole-proxy-caddyfile}
    file: ./config/Caddyfile
