services:
  pihole:
    image: ${IMAGE_NAME:-pihole/pihole}:${IMAGE_TAG:-latest}
    environment:
      TZ:
      ADMIN_EMAIL:
      WEBPASSWORD:
      WEB_PORT:
      FTLCONF_LOCAL_IPV4:
      FTLCONF_LOCAL_IPV6:
      IPv6:
      PIHOLE_DNS_:
      DNSMASQ_LISTENING:
      DNSSEC:
      DNS_BOGUS_PRIV:
      DNS_FQDN_REQUIRED:
      REV_SERVER:
      REV_SERVER_DOMAIN:
      REV_SERVER_TARGET:
      REV_SERVER_CIDR:
    networks:
      host-net:
    cap_add:
      - NET_RAW
      - NET_BIND_SERVICE
      - SYS_NICE
      - CHOWN
    volumes:
      - pihole-vol:/etc/pihole
      - dnsmasqd-vol:/etc/dnsmasq.d
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - ${PLACEMENT_CONSTRAINTS_NAME:-node.hostname} ${PLACEMENT_CONSTRAINTS_OPERATOR:-==} ${PLACEMENT_CONSTRAINTS_VALUE:-node}
      restart_policy:
        delay: ${RESTART_DELAY:-1s}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-512M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.01}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-256M}
